### ISSUE TITLE
[Content] Add link to contribute

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#16]
Add the text "Contribute to Coding Playlists →" aligned to the right under the header and link it to https://github.com/gracekishino/coding_playlists (opens in a new tab).

**Comment by Jainil2004** [comment]
hi @gracekishino, I am interested in contributing to your project and would love to solve this issue. could you please assign this issue to me? as I am interested in solving this issue.
Thanks

**Comment by gracekishino** [comment]
@Jainil2004 thanks so much! You are assigned :)

**Comment by Jainil2004** [comment]
hi @gracekishino, so i was traveling for the past two days, sorry for not reporting to you early about this. I'll start right away with this issue on priority basis, I hope you understand. Also can you please tell me like any is there any specific thing you would like me to address in this issue? or like tell me how should I proceed.
Thank you

**Comment by Jainil2004** [comment]
hi @gracekishino, thank you for the steps to make the update. I have another query which is related to styling. do I also have to make modifications in the style.css file? or only the index.html file?
thank you

**Comment by Jainil2004** [comment]
@gracekishino, I have completed this issue and just wanted to give you a preview of the work before actually submitting a PR. so that you can provide me with your valuable feedback and makes changes if something seems out of place.
Based on my understanding, the issue was to add a link that links to the original repository inside the header tag. Now since no context was provided about what type of tag was supposed to be used other than the anchor tag. I compared the tags myself and used the one which I felt perfect. I have attached screenshots related to the issue 

code:
![image](https://github.com/gracekishino/coding_playlists/assets/112818722/506423f8-d794-4b74-be28-b5273202311b)


output:
![image](https://github.com/gracekishino/coding_playlists/assets/112818722/ec507ef0-8419-4f48-a545-da29d9f85a8d)

please have a look and do let me know if any changes are to be made. I'll be very happy to help. Thank you so much for providing me with this opportunity.

**Comment by Jainil2004** [comment]
@gracekishino also if you are satisfied with my work. let me know and I'll generate a PR ASAP
Thank you

**Comment by Jainil2004** [comment]
hi @gracekishino thank you for your valuable review. Based of your review, I will move the styling part into the style.css file and will also generate a PR which will provide you with all the changes I've made.
Thank you

**Comment by Jainil2004** [comment]
@gracekishino I observed one thing in the code snippet you provided that is we are setting the color as #fff but if you look in the code I've written the id traces back to the H4 heading housing the anchor link. So by setting the color nothing actually happens as the text is part of the anchor link and not the heading link. so my question is do we want to change the text color inside the anchor tag to white or not ?

**Comment by gracekishino** [comment]
@Jainil2004 thanks for catching that! Yes I wanted the text in the anchor to be white, so something similar to this:

```
#contribution_link {
   text-align: right;
}

#contribution_link a {
   color: #fff;
   text-decoration: none;
}
```

**Comment by Jainil2004** [comment]
@gracekishino I have completed all the minor changes. here is a small preview of how the things look now. please note that there is actually no difference in the overall appearance of the project page. the only change is complete movement of styling portion from html source file to the css source file. please have a look and provide me with details if there is a need to change something.

**changes in code:**
**1. index.html**: removed styling from the HTML
![image](https://github.com/gracekishino/coding_playlists/assets/112818722/0065194a-5e1c-413d-a451-ac404e7bf3cf)

**2. style.css**: added styling for the contribute link
![image](https://github.com/gracekishino/coding_playlists/assets/112818722/231ff7ab-ccf1-441c-b265-e348b658afab)

**Comment by Jainil2004** [comment]
@gracekishino I will generate a PR once you authorize these changes. 
Thank you

**Comment by Jainil2004** [comment]
@gracekishino thank you so much for clarifying that. I'll work on that portion now and will get back to you soon with the desired changes requested by you.

**Comment by gracekishino** [comment]
@Jainil2004 Thank you! 

By the way we can we can do a code review from a pull request, so it's OK to submit a pull request with the changes even if they haven't been checked by a maintainer first.

**Comment by Jainil2004** [comment]
@gracekishino I have made minor changes to the code. please have a look at the changes in the code. Also i will submit a PR so that you can code review from the pull request.

**Comment by Jainil2004** [comment]
@gracekishino I have submitted a PR. please have a look and do let me know if any changes are required to be made. I will be very happy to help. Thank you
