### ISSUE TITLE
[Content] Add a YouTube music playlist

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#2]
Create a new section in `index.html` for YouTube music playlists and add a playlist under it.

**Comment by MelindaH26** [comment]
I have a couple of relaxing/focus music videos I've been using for study that I could add here

**Comment by gracekishino** [comment]
@MelindaH26 that would be great! Let me know if you need any help with anything or have any questions, etc. 😊

**Comment by MelindaH26** [comment]
Thanks @gracekishino! Will do :) I will get to work on it soon!
