### ISSUE TITLE
[Layout] Make Spotify Section Responsive 

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#20]
Update Spotify section to be responsive like the YouTube section. 

Can refer to this pull request for the YouTube section by @MelindaH26  on how to update the code:
https://github.com/gracekishino/coding_playlists/pull/19/files

**Comment by ElenaExposito** [comment]
Hi @gracekishino,  can I take this issue?

**Comment by gracekishino** [comment]
@ElenaExposito Yes thanks again! I have assigned you :)
