### ISSUE TITLE
[Content] Add intro text

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#21]
Add this text inside a `<div>` tag to the top of the `<main>` section in `index.html` so it appears at the top of the page, just under the header:

> Welcome to "Coding Playlists" – a laid-back space where the coding community comes together to share and discover chill soundtracks for productive coding vibes.

**Comment by ElenaExposito** [comment]
Hey @gracekishino! Can I take this issue?

**Comment by gracekishino** [comment]
@ElenaExposito yes thanks so much! You are assigned and I'll check out the merge request now :)
