### ISSUE TITLE
[Contributing] Create a PR template

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#26]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Jainil2004** [comment]
hello @gracekishino, I am really loving the way the project is improving day by day and hence I would love to volunteer for the creation of the PR template for this project. Please assign this issue to me, would be really happy to help.
thank you

**Comment by gracekishino** [comment]
@Jainil2004 thanks so much! 

Let's put it in a `.github` folder like this PR template for Codecademy Docs https://github.com/Codecademy/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1

You can also use ideas from the Codecademy Docs PR template, but it can be simpler. 
Let me know if you want more pointer on how to do this!

**Comment by Jainil2004** [comment]
@gracekishino understood. I'll start working on the template and will submit a PR as soon as I am done and satisfied with the PR template. Also thanks for assigning :)
