### ISSUE TITLE
[Content] Add link to text

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#41]
Link the text below in `index.html` to open in a new window and go to https://github.com/gracekishino/coding_playlists:

> coding community comes together

**Comment by madina0801** [comment]
Hi! Could you please assign this to me? :)

**Comment by gracekishino** [comment]
Thanks! You're assigned :)

**Comment by gracekishino** [comment]
@madina0801 thanks for completing this so quickly! You can see the change live here :) https://coding-playlists.netlify.app
