### ISSUE TITLE
[Layout] Highlight current section button in the header

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#42]
Use Javscript to highlight the current section's button in the header

**Comment by Anmol-Gup** [comment]
Hi @gracekishino, is this thing you are looking out for?
If yes, please assign me this.

https://github.com/gracekishino/coding_playlists/assets/66009201/3664e132-504e-4bae-8a09-8cb0e16eaf70

**Comment by gracekishino** [comment]
Yes that's what I'm looking for! Thanks so much, have assigned you.

**Comment by gracekishino** [comment]
@Anmol-Gup thanks for doing this! You can see the changes live here: https://coding-playlists.netlify.app
